services:
  backend:
    image: ${DOCKER_IMAGE}
    platform: linux/amd64
    container_name: haloop-backend
    ports:
      - "3000:3000"
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - nginx-proxy
    volumes:
      - app-logs:/app/logs

  init-opensearch:
    image: ${DOCKER_IMAGE}
    command: node dist/services/elasticsearch/initOpensearch.js
    env_file:
      - .env.production
networks:
  nginx-proxy:
    external: true

volumes:
  app-logs:
